/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as ProektyRouteImport } from './routes/proekty'
import { Route as ProNasRouteImport } from './routes/pro-nas'
import { Route as NovynyRouteImport } from './routes/novyny'
import { Route as InformatsiiaDliaZmiRouteImport } from './routes/informatsiia-dlia-zmi'
import { Route as GromadskaSpilkaRouteImport } from './routes/gromadska-spilka'
import { Route as GalereiaRouteImport } from './routes/galereia'
import { Route as DopomogtyRouteImport } from './routes/dopomogty'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProektyIndexRouteImport } from './routes/proekty.index'
import { Route as NovynyIndexRouteImport } from './routes/novyny.index'
import { Route as GalereiaIndexRouteImport } from './routes/galereia.index'
import { Route as ProektySlugRouteImport } from './routes/proekty.$slug'
import { Route as NovynySlugRouteImport } from './routes/novyny.$slug'
import { Route as GalereiaSlugRouteImport } from './routes/galereia.$slug'
import { Route as ApiSanityRedeployRouteImport } from './routes/api.sanity-redeploy'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ProektyRoute = ProektyRouteImport.update({
  id: '/proekty',
  path: '/proekty',
  getParentRoute: () => rootRouteImport,
} as any)
const ProNasRoute = ProNasRouteImport.update({
  id: '/pro-nas',
  path: '/pro-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const NovynyRoute = NovynyRouteImport.update({
  id: '/novyny',
  path: '/novyny',
  getParentRoute: () => rootRouteImport,
} as any)
const InformatsiiaDliaZmiRoute = InformatsiiaDliaZmiRouteImport.update({
  id: '/informatsiia-dlia-zmi',
  path: '/informatsiia-dlia-zmi',
  getParentRoute: () => rootRouteImport,
} as any)
const GromadskaSpilkaRoute = GromadskaSpilkaRouteImport.update({
  id: '/gromadska-spilka',
  path: '/gromadska-spilka',
  getParentRoute: () => rootRouteImport,
} as any)
const GalereiaRoute = GalereiaRouteImport.update({
  id: '/galereia',
  path: '/galereia',
  getParentRoute: () => rootRouteImport,
} as any)
const DopomogtyRoute = DopomogtyRouteImport.update({
  id: '/dopomogty',
  path: '/dopomogty',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProektyIndexRoute = ProektyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProektyRoute,
} as any)
const NovynyIndexRoute = NovynyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovynyRoute,
} as any)
const GalereiaIndexRoute = GalereiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalereiaRoute,
} as any)
const ProektySlugRoute = ProektySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProektyRoute,
} as any)
const NovynySlugRoute = NovynySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NovynyRoute,
} as any)
const GalereiaSlugRoute = GalereiaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalereiaRoute,
} as any)
const ApiSanityRedeployRoute = ApiSanityRedeployRouteImport.update({
  id: '/api/sanity-redeploy',
  path: '/api/sanity-redeploy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/dopomogty': typeof DopomogtyRoute
  '/galereia': typeof GalereiaRouteWithChildren
  '/gromadska-spilka': typeof GromadskaSpilkaRoute
  '/informatsiia-dlia-zmi': typeof InformatsiiaDliaZmiRoute
  '/novyny': typeof NovynyRouteWithChildren
  '/pro-nas': typeof ProNasRoute
  '/proekty': typeof ProektyRouteWithChildren
  '/video': typeof VideoRoute
  '/api/sanity-redeploy': typeof ApiSanityRedeployRoute
  '/galereia/$slug': typeof GalereiaSlugRoute
  '/novyny/$slug': typeof NovynySlugRoute
  '/proekty/$slug': typeof ProektySlugRoute
  '/galereia/': typeof GalereiaIndexRoute
  '/novyny/': typeof NovynyIndexRoute
  '/proekty/': typeof ProektyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/dopomogty': typeof DopomogtyRoute
  '/gromadska-spilka': typeof GromadskaSpilkaRoute
  '/informatsiia-dlia-zmi': typeof InformatsiiaDliaZmiRoute
  '/pro-nas': typeof ProNasRoute
  '/video': typeof VideoRoute
  '/api/sanity-redeploy': typeof ApiSanityRedeployRoute
  '/galereia/$slug': typeof GalereiaSlugRoute
  '/novyny/$slug': typeof NovynySlugRoute
  '/proekty/$slug': typeof ProektySlugRoute
  '/galereia': typeof GalereiaIndexRoute
  '/novyny': typeof NovynyIndexRoute
  '/proekty': typeof ProektyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/dopomogty': typeof DopomogtyRoute
  '/galereia': typeof GalereiaRouteWithChildren
  '/gromadska-spilka': typeof GromadskaSpilkaRoute
  '/informatsiia-dlia-zmi': typeof InformatsiiaDliaZmiRoute
  '/novyny': typeof NovynyRouteWithChildren
  '/pro-nas': typeof ProNasRoute
  '/proekty': typeof ProektyRouteWithChildren
  '/video': typeof VideoRoute
  '/api/sanity-redeploy': typeof ApiSanityRedeployRoute
  '/galereia/$slug': typeof GalereiaSlugRoute
  '/novyny/$slug': typeof NovynySlugRoute
  '/proekty/$slug': typeof ProektySlugRoute
  '/galereia/': typeof GalereiaIndexRoute
  '/novyny/': typeof NovynyIndexRoute
  '/proekty/': typeof ProektyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contacts'
    | '/dopomogty'
    | '/galereia'
    | '/gromadska-spilka'
    | '/informatsiia-dlia-zmi'
    | '/novyny'
    | '/pro-nas'
    | '/proekty'
    | '/video'
    | '/api/sanity-redeploy'
    | '/galereia/$slug'
    | '/novyny/$slug'
    | '/proekty/$slug'
    | '/galereia/'
    | '/novyny/'
    | '/proekty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contacts'
    | '/dopomogty'
    | '/gromadska-spilka'
    | '/informatsiia-dlia-zmi'
    | '/pro-nas'
    | '/video'
    | '/api/sanity-redeploy'
    | '/galereia/$slug'
    | '/novyny/$slug'
    | '/proekty/$slug'
    | '/galereia'
    | '/novyny'
    | '/proekty'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contacts'
    | '/dopomogty'
    | '/galereia'
    | '/gromadska-spilka'
    | '/informatsiia-dlia-zmi'
    | '/novyny'
    | '/pro-nas'
    | '/proekty'
    | '/video'
    | '/api/sanity-redeploy'
    | '/galereia/$slug'
    | '/novyny/$slug'
    | '/proekty/$slug'
    | '/galereia/'
    | '/novyny/'
    | '/proekty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactsRoute: typeof ContactsRoute
  DopomogtyRoute: typeof DopomogtyRoute
  GalereiaRoute: typeof GalereiaRouteWithChildren
  GromadskaSpilkaRoute: typeof GromadskaSpilkaRoute
  InformatsiiaDliaZmiRoute: typeof InformatsiiaDliaZmiRoute
  NovynyRoute: typeof NovynyRouteWithChildren
  ProNasRoute: typeof ProNasRoute
  ProektyRoute: typeof ProektyRouteWithChildren
  VideoRoute: typeof VideoRoute
  ApiSanityRedeployRoute: typeof ApiSanityRedeployRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proekty': {
      id: '/proekty'
      path: '/proekty'
      fullPath: '/proekty'
      preLoaderRoute: typeof ProektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-nas': {
      id: '/pro-nas'
      path: '/pro-nas'
      fullPath: '/pro-nas'
      preLoaderRoute: typeof ProNasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novyny': {
      id: '/novyny'
      path: '/novyny'
      fullPath: '/novyny'
      preLoaderRoute: typeof NovynyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informatsiia-dlia-zmi': {
      id: '/informatsiia-dlia-zmi'
      path: '/informatsiia-dlia-zmi'
      fullPath: '/informatsiia-dlia-zmi'
      preLoaderRoute: typeof InformatsiiaDliaZmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gromadska-spilka': {
      id: '/gromadska-spilka'
      path: '/gromadska-spilka'
      fullPath: '/gromadska-spilka'
      preLoaderRoute: typeof GromadskaSpilkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galereia': {
      id: '/galereia'
      path: '/galereia'
      fullPath: '/galereia'
      preLoaderRoute: typeof GalereiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dopomogty': {
      id: '/dopomogty'
      path: '/dopomogty'
      fullPath: '/dopomogty'
      preLoaderRoute: typeof DopomogtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proekty/': {
      id: '/proekty/'
      path: '/'
      fullPath: '/proekty/'
      preLoaderRoute: typeof ProektyIndexRouteImport
      parentRoute: typeof ProektyRoute
    }
    '/novyny/': {
      id: '/novyny/'
      path: '/'
      fullPath: '/novyny/'
      preLoaderRoute: typeof NovynyIndexRouteImport
      parentRoute: typeof NovynyRoute
    }
    '/galereia/': {
      id: '/galereia/'
      path: '/'
      fullPath: '/galereia/'
      preLoaderRoute: typeof GalereiaIndexRouteImport
      parentRoute: typeof GalereiaRoute
    }
    '/proekty/$slug': {
      id: '/proekty/$slug'
      path: '/$slug'
      fullPath: '/proekty/$slug'
      preLoaderRoute: typeof ProektySlugRouteImport
      parentRoute: typeof ProektyRoute
    }
    '/novyny/$slug': {
      id: '/novyny/$slug'
      path: '/$slug'
      fullPath: '/novyny/$slug'
      preLoaderRoute: typeof NovynySlugRouteImport
      parentRoute: typeof NovynyRoute
    }
    '/galereia/$slug': {
      id: '/galereia/$slug'
      path: '/$slug'
      fullPath: '/galereia/$slug'
      preLoaderRoute: typeof GalereiaSlugRouteImport
      parentRoute: typeof GalereiaRoute
    }
    '/api/sanity-redeploy': {
      id: '/api/sanity-redeploy'
      path: '/api/sanity-redeploy'
      fullPath: '/api/sanity-redeploy'
      preLoaderRoute: typeof ApiSanityRedeployRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GalereiaRouteChildren {
  GalereiaSlugRoute: typeof GalereiaSlugRoute
  GalereiaIndexRoute: typeof GalereiaIndexRoute
}

const GalereiaRouteChildren: GalereiaRouteChildren = {
  GalereiaSlugRoute: GalereiaSlugRoute,
  GalereiaIndexRoute: GalereiaIndexRoute,
}

const GalereiaRouteWithChildren = GalereiaRoute._addFileChildren(
  GalereiaRouteChildren,
)

interface NovynyRouteChildren {
  NovynySlugRoute: typeof NovynySlugRoute
  NovynyIndexRoute: typeof NovynyIndexRoute
}

const NovynyRouteChildren: NovynyRouteChildren = {
  NovynySlugRoute: NovynySlugRoute,
  NovynyIndexRoute: NovynyIndexRoute,
}

const NovynyRouteWithChildren =
  NovynyRoute._addFileChildren(NovynyRouteChildren)

interface ProektyRouteChildren {
  ProektySlugRoute: typeof ProektySlugRoute
  ProektyIndexRoute: typeof ProektyIndexRoute
}

const ProektyRouteChildren: ProektyRouteChildren = {
  ProektySlugRoute: ProektySlugRoute,
  ProektyIndexRoute: ProektyIndexRoute,
}

const ProektyRouteWithChildren =
  ProektyRoute._addFileChildren(ProektyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactsRoute: ContactsRoute,
  DopomogtyRoute: DopomogtyRoute,
  GalereiaRoute: GalereiaRouteWithChildren,
  GromadskaSpilkaRoute: GromadskaSpilkaRoute,
  InformatsiiaDliaZmiRoute: InformatsiiaDliaZmiRoute,
  NovynyRoute: NovynyRouteWithChildren,
  ProNasRoute: ProNasRoute,
  ProektyRoute: ProektyRouteWithChildren,
  VideoRoute: VideoRoute,
  ApiSanityRedeployRoute: ApiSanityRedeployRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
