/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as ProektyRouteImport } from './routes/proekty'
import { Route as ProNasRouteImport } from './routes/pro-nas'
import { Route as NovynyRouteImport } from './routes/novyny'
import { Route as InformatsiiaDliaZmiRouteImport } from './routes/informatsiia-dlia-zmi'
import { Route as GromadskaSpilkaRouteImport } from './routes/gromadska-spilka'
import { Route as DopomogtyRouteImport } from './routes/dopomogty'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ProektyRoute = ProektyRouteImport.update({
  id: '/proekty',
  path: '/proekty',
  getParentRoute: () => rootRouteImport,
} as any)
const ProNasRoute = ProNasRouteImport.update({
  id: '/pro-nas',
  path: '/pro-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const NovynyRoute = NovynyRouteImport.update({
  id: '/novyny',
  path: '/novyny',
  getParentRoute: () => rootRouteImport,
} as any)
const InformatsiiaDliaZmiRoute = InformatsiiaDliaZmiRouteImport.update({
  id: '/informatsiia-dlia-zmi',
  path: '/informatsiia-dlia-zmi',
  getParentRoute: () => rootRouteImport,
} as any)
const GromadskaSpilkaRoute = GromadskaSpilkaRouteImport.update({
  id: '/gromadska-spilka',
  path: '/gromadska-spilka',
  getParentRoute: () => rootRouteImport,
} as any)
const DopomogtyRoute = DopomogtyRouteImport.update({
  id: '/dopomogty',
  path: '/dopomogty',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/dopomogty': typeof DopomogtyRoute
  '/gromadska-spilka': typeof GromadskaSpilkaRoute
  '/informatsiia-dlia-zmi': typeof InformatsiiaDliaZmiRoute
  '/novyny': typeof NovynyRoute
  '/pro-nas': typeof ProNasRoute
  '/proekty': typeof ProektyRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/dopomogty': typeof DopomogtyRoute
  '/gromadska-spilka': typeof GromadskaSpilkaRoute
  '/informatsiia-dlia-zmi': typeof InformatsiiaDliaZmiRoute
  '/novyny': typeof NovynyRoute
  '/pro-nas': typeof ProNasRoute
  '/proekty': typeof ProektyRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/dopomogty': typeof DopomogtyRoute
  '/gromadska-spilka': typeof GromadskaSpilkaRoute
  '/informatsiia-dlia-zmi': typeof InformatsiiaDliaZmiRoute
  '/novyny': typeof NovynyRoute
  '/pro-nas': typeof ProNasRoute
  '/proekty': typeof ProektyRoute
  '/video': typeof VideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contacts'
    | '/dopomogty'
    | '/gromadska-spilka'
    | '/informatsiia-dlia-zmi'
    | '/novyny'
    | '/pro-nas'
    | '/proekty'
    | '/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contacts'
    | '/dopomogty'
    | '/gromadska-spilka'
    | '/informatsiia-dlia-zmi'
    | '/novyny'
    | '/pro-nas'
    | '/proekty'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contacts'
    | '/dopomogty'
    | '/gromadska-spilka'
    | '/informatsiia-dlia-zmi'
    | '/novyny'
    | '/pro-nas'
    | '/proekty'
    | '/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactsRoute: typeof ContactsRoute
  DopomogtyRoute: typeof DopomogtyRoute
  GromadskaSpilkaRoute: typeof GromadskaSpilkaRoute
  InformatsiiaDliaZmiRoute: typeof InformatsiiaDliaZmiRoute
  NovynyRoute: typeof NovynyRoute
  ProNasRoute: typeof ProNasRoute
  ProektyRoute: typeof ProektyRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proekty': {
      id: '/proekty'
      path: '/proekty'
      fullPath: '/proekty'
      preLoaderRoute: typeof ProektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-nas': {
      id: '/pro-nas'
      path: '/pro-nas'
      fullPath: '/pro-nas'
      preLoaderRoute: typeof ProNasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novyny': {
      id: '/novyny'
      path: '/novyny'
      fullPath: '/novyny'
      preLoaderRoute: typeof NovynyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informatsiia-dlia-zmi': {
      id: '/informatsiia-dlia-zmi'
      path: '/informatsiia-dlia-zmi'
      fullPath: '/informatsiia-dlia-zmi'
      preLoaderRoute: typeof InformatsiiaDliaZmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gromadska-spilka': {
      id: '/gromadska-spilka'
      path: '/gromadska-spilka'
      fullPath: '/gromadska-spilka'
      preLoaderRoute: typeof GromadskaSpilkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dopomogty': {
      id: '/dopomogty'
      path: '/dopomogty'
      fullPath: '/dopomogty'
      preLoaderRoute: typeof DopomogtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactsRoute: ContactsRoute,
  DopomogtyRoute: DopomogtyRoute,
  GromadskaSpilkaRoute: GromadskaSpilkaRoute,
  InformatsiiaDliaZmiRoute: InformatsiiaDliaZmiRoute,
  NovynyRoute: NovynyRoute,
  ProNasRoute: ProNasRoute,
  ProektyRoute: ProektyRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
